### ISSUE TITLE
Pb compatibilité IE

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#1]
Tu as bien précisé que l'application était faite pour tablette.
Donc forcément, j'ai testé sur PC IE 11
=> écran vide
![Capture](https://user-images.githubusercontent.com/34870193/61868951-d0c22a00-aeda-11e9-8aa3-6d9b4a61d737.JPG)

SCRIPT5009: « Promise » est indéfini

	        	Promise.all([
                    Utils.load.css('resources/css/body.css'),

**Comment by rafdulaf** [comment]
Je vais prévoir un bel écran pour jeter les gens qui utilisent par un navigateur supporté :)

J'ai volontairement utilisé des technos HTML/CSS récentes pour aller vite : donc ma cible c'est de supporte les navigateurs mainstream seulement (pour les particuliers) 
* dernière version de chrome
* dernière version de ff
* dernière version de safari

**Comment by rafdulaf** [comment]
l'écran sera là... mais pas bo du tout :D
