### ISSUE TITLE
Interface Cartes dynamiques / Surplomb

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#10]
L'indication des bonus de surplomb via des nuances de couleur n'est pas intuitive. On dirait deux nuances de vert très proches.
Suggestions : 
- Accentuer la différence de teinte (par ex. Vert et Jaune, cf. les cartes dynamiques Batman de Pamplerousse)
- Changer la couleur des traits en fonction (cf. les cartes dynamiques Batman Pamplerousse), 
et/ou: 
- Ajouter une icône "Dé jaune" sur les zones concernées lorsqu'elles s'affichent.

**Comment by madcollectordev** [comment]
Je m'étais fait la même réflexion. Merci @RoolzTOL

**Comment by rafdulaf** [comment]
moi aussi :)
j'avais pensé au dé jaune, mais j'avais eu la flemme à l'époque

la couleur, j'avais testé "jaune jaune" et ça faisait un peu genre "avertissement"...
je vais jaunir un peu plus, et ajouter le dé

la couleur des traites, j'y avais pas pensé par contre et c'est une bonne idée! (ça sera léger là aussi - mais le dé jaune tranchera tout doute)

**Comment by rafdulaf** [comment]
Finalement, un jaune plus tranché. Des lignes de couleurs différentes selon la hauteur.
Du coup les zones plus élevées, qui avaient déjà une couleur différente sont maintenant plus tranchées aussi (et j'ai ajouté une explication dans l'aide)
