### ISSUE TITLE
Cartes : changement d'icones selon l'onglet

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#12]
Bug ou Feature ?
Sur une carte, l'onglet "Lignes de vues" propose le téléchargement de la carte statique
![image](https://user-images.githubusercontent.com/34870193/62234847-d1bbf580-b3cb-11e9-825b-03515fc20805.png)

L'onglet "Aide de jeu" propose ce téléchargement avec une autre icone, ainsi qu'un lien vers le forum qui n'était pas sur le premier onglet
![image](https://user-images.githubusercontent.com/34870193/62234960-1b0c4500-b3cc-11e9-9956-35c2e1640f90.png)

Cette inconsistance peut étonner l'utilisateur

**Comment by rafdulaf** [comment]
C'est normal que les icones changent... mais il y a un bug en effet, car les fonctions changent aussi :) et au minimum le "title" affiché pour le lien est faux :)
bien vu

**Comment by rafdulaf** [comment]
oui c'est bien le nom du bouton qui est erroné.
En fait c'était même déjà corrigé, mais pas encore déployé.
