### ISSUE TITLE
Navigation Cartes

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#15]
Sur PC Firefox 68
J'affiche les lignes de vue de la carte Village Picte

En bas de la fenêtre, on pourrait croire que le bouton "Cartes" ramène au sommaire des cartes (comme le bouton en haut à droite dans la barre rouge)
Mais il ne fait rien
![image](https://user-images.githubusercontent.com/34870193/62653452-e5cc9d80-b95d-11e9-83e2-2a829257524a.png)

**Comment by rafdulaf** [comment]
Les "boutons" du bas sont en fait des onglets : c'est le rendu material design (+ ou -) des barres de navigation.

Le cas d'utilisation principal de l'application c'est qu'au fil de la partie, l'utilisateur est censé se promener entre les onglets cartes, règles et scénario... L'utilisateur, ne veut pas revenir au scénario par défaut, ni à la racine des cartes à chaque fois.
Et il est très rare (en dehors des tests) de vouloir revenir à l'accueil des cartes : seulement à la fin d'une partie, si on enchaîne avec une autre partie sur un plateau différent.

Et encore, je pense que le choix d'un scénario pré-sélectionnera automatiquement la carte...

Du coup, je ne pense pas changer ce comportement. Est-tu d'accord avec ce que je dis ?

**Comment by madcollectordev** [comment]
Je signale juste que ça peut être déroutant pour l'utilisateur. Si il clique sur Règles, ça l'envoie au sommaire des règles. Il pourrait s'attendre au même comportement avec le lien Cartes, même s'il est déjà sur une carte

**Comment by rafdulaf** [comment]
Alors, sur règles, c'est tout pareil, il te remet dans l'état dans lequel tu as quitté "règles".
Si tu es sur les "livre des heros" par ex, tu y reviendras. Si tu es sur les compétences et que tu as scrollé jusqu'à "Magie", tu y reviendras aussi.

Tout reste en l'état dans chaque onglet.
Du coup pour moi c'est cohérent

**Comment by madcollectordev** [comment]
Ah OK j'avais pas vu"l'empilement" des sections, et le retour là où on était dans chaque section.
Du coup j'ai rien dit, tu peux clôturer.
