### ISSUE TITLE
EN - Orthographe etc.

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#16]
Ecran "Boards" (accueil)

**Stygia**
_C'est bien Stygie en FR._

Ecran "Rules"

**Heroes'** book - **Overlord's** book
_Manque les aporstrophes. Et on ne met pas de "s" si le mot se termine par s, juste l'apostrophe._

Ecran "Legend"

Blue area is the selected area.
Blue area has line of sight to all colored areas.
Yellow areas are below the blue area: Ranged attacks to these areas get an Elevation bonus of 1 yellow die.
Green areas are at the same level as the blue area.
Turquoise areas are above the blue area.
Note: The green circles around the dots show elevation levels. 

_Proposition de reformulation._

**Comment by rafdulaf** [comment]
> **Heroes'** book - **Overlord's** book
> _Manque les aporstrophes. Et on ne met pas de "s" si le mot se termine par s, juste l'apostrophe._

Je les ai mises, mais la police de caractères ne les gère pas. 
De même je n'ai aucun accent en français. Et elle ne gère aucune ponctuation non plus.
J'avais fais une croix dessus, mais si ça te parait illisible en anglais du coup, je verrais si je peux faire un hack....

**Comment by rafdulaf** [comment]
pour les reste ok.

**Comment by RoolzTOL** [comment]
Pour la police, il faut que tu prennes la "Hyborian", elle a accents, apostrophes, ponctuation, etc (la police Crom qui y ressemble beaucoup n'a pas les accents etc). 
Tu peux la trouver sur the-overlord dans le package de polices Conan (Conan->Téléchargement->Ressources).

**Comment by RoolzTOL** [comment]
Tu peux aussi utiliser la police "CrushYourEnemies" qui est similaire, elle aussi a accents etc (elle est sur fontspace.com).
Elle est récente, je ne l'ai pas testée, mais elle rendra peut-être mieux que la Hyborian sur écran.

**Comment by rafdulaf** [comment]
super ça. je vais tester ! Merci

**Comment by rafdulaf** [comment]
> Blue area is the selected area.
> Blue area has line of sight to all colored areas.
J'ai réuni en une seule phrase : Blue area is the selected area. It has lines of sight to all colored areas.
C'est correct ?

> Pour la police, il faut que tu prennes la "Hyborian"
J'ai utilisé Hyborian, car elle fait le job. Merci de la recommandation, c'est cool d'avoir les accents !!!
