### ISSUE TITLE
EN-FR - Swamp-Marais

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#17]
Ecran Swamp/Marais, Règles du plateau/Board rules

Suggestion d'indiquer les zones d'eau (1) sur la mini-carte. 
Ca fait partie des trucs pas vraiment explicites sur ce plateau...

**Comment by rafdulaf** [comment]
Je viens de regarder en détail et je suis assez dubitatif. Tu veux localiser la 30 aines de cases d'eau ??? ça va rendre la carte illisible je pense: car déjà sur un grand écran, il y aurait pas la place de mettre les "1" dans les petites cases, mais sur une tablette ou un téléphone, c'est mort.

Tu penses à quoi comme case qui n'est pas explicitement de l'eau ? la seule qui pose un doute pour moi c'est à droite, le ponton affaissé au milieu, mais ce n'est justement pas de l'eau...

**Comment by RoolzTOL** [comment]
Oui c'est pas faux, ça va surcharger le truc. Il doit y avoir 24 zones d'eau....
 
Si je ne m'abuse celles qui ne sont pas de l'eau sont toutes les zones de bois du village (pontons, cabanes), les 4 zones de pierre (autels), et les 3 zones où il y a les escaliers d'accès.

Mais visuellement, il y a qq zones qui contiennent plus de "plantes/gazon" que d'eau (idem que les 3 zones d'escaliers). Sur celles-ci je trouve que c'est pas explicite (2 zones tout en bas à gauche, et 2 zones tout en haut au milieu, 1 zone en haut à droite entre une cabane et la plateforme). Mais c'est peut-être juste moi.

Sur ce, je serai en congés jusqu'à fin aout, avec accès limité à internet. Donc si je ne réponds pas c'est normal :) 
A+ et bon courage pour la suite !

**Comment by rafdulaf** [comment]
merci et bonnes vancances
je vais aussi être en congé très bientot

**Comment by RoolzTOL** [comment]
Je viens de penser à un truc. 
Plutôt que de mettre une chiée de "1" sur chaque case eau, ce qui rendrait la chose illisible sur la mini-carte, peut être qu'en matérialisant ces cases...
- via une couleur (cf le bleu de ma map statique en PJ), 
- ou via des contours en pointillés (cf le croquis en PJ, en version moins dégueu et avec des pointillés)
...ça serait plus lisible ?

![board_marais](https://user-images.githubusercontent.com/53515040/64854371-c6d8bf80-d61d-11e9-8d49-ffecda8c6c95.png)

![CONAN_SG - board - swampLOS03](https://user-images.githubusercontent.com/53515040/64854254-7bbeac80-d61d-11e9-8e0f-79f6e2cbe18a.jpg)

**Comment by rafdulaf** [comment]
Voilà. J'ai choisi la version avec les zones turquoises comme la carte statique.
Tu me diras ce que tu en penses quand je déploierai la livraison

**Comment by RoolzTOL** [comment]
OK, tiens-moi au jus.
