### ISSUE TITLE
Affichage titre "Règle du plateau" version mobile

### ISSUE THREAD

**Issue by Renand** [rafdulaf/companion4conan#18]
Le titre est tronqué dans la version mobile.

Règles du plateau devient **Règles du**
<img width="347" alt="Capture d’écran 2019-08-12 à 10 14 38" src="https://user-images.githubusercontent.com/738859/62852618-36d7eb00-bcea-11e9-8de1-476037cad977.png">

**Comment by rafdulaf** [comment]
L'objectif principal c'est les tablettes.
Mais j'essaie de faire le plus possible pour que ça soit utilisable sur téléphone aussi.
Donc je vais voir ce que je peux faire là dessus.

**Comment by Renand** [comment]
Deux lignes ou une media query sur la taille de font ?

**Comment by rafdulaf** [comment]
Voilà. J'ai envoyé une correction qui sera visible à la prochaine mise à jour.
J'ai fait une media query pour diminuer la taille de police, puis le line-height pour passer sur deux ligne.

Comme je fais la même règle pour tous les onglets, parfois on peut avoir l'impression que cela "saute" trop tôt ; mais au moins tout est toujours lisible. C'est l'essentiel.

Et j'ai appris au passage l'existence d'une vieille balise dont j'ignorais l'existence alors que ça fait une paye que je fais du HTML/CSS : <wbr/> pour Word Break Opportunity qui indique au navigateur une césure possible pour un mot. (Je l'ai utilisé sur le mot Equipement dans l'onglet Studio)

**Comment by Renand** [comment]
merci, effectivement c'est une balise arrivée avec HTML5, je n'ai jamais utilisé ça :)
