### ISSUE TITLE
Affichages Règles plateau

### ISSUE THREAD

**Issue by Renand** [rafdulaf/companion4conan#19]
![image](https://user-images.githubusercontent.com/738859/62855796-6f2ff700-bcf3-11e9-86ba-290a0092b994.png)

Je me demande si il ne serait pas plus confortable pour la lisibilité de remplacer les puces numérotées par des couleurs ?

**Comment by rafdulaf** [comment]
les deux alors.
il faut respecter les gens qui ont des difficultés visuelles :) (j'ai une formation dans accessibilité du web)

mais tu as raison, cela permettrait de repérer plus rapidement sur le carte.

j'ai aussi pensé à un clic sur la légende pour mettre en surbrillance sur la carte 
et inversement, unclic sur un chiffre de la caerte pour scroller sur la bonne légende sur mobile.

**Comment by Renand** [comment]
Oui bien sur, pour l'accessibilité. Au final c'est pour cette raison que le besoin de couleur se fait sentir chez moi, je suis franchement dyslexique.

**Comment by rafdulaf** [comment]
Voilà ce que ça donne. A découvrir quand je livrerai la 0.3
![image](https://user-images.githubusercontent.com/1202407/66161736-4827de80-e62d-11e9-82e9-eca60b35d086.png)
