### ISSUE TITLE
Pas de zoom [Fixed in 0.2]

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#2]
Testé sur tablette Samsung Galaxy Tab, sur Chrome et Firefox Beta
Impossible de zoomer/pincher
Peut être problématique pour les personnes ayant des mauvais yeux ou utilisant la tablette dans la pénombre sans augmenter la luminosité.

**Comment by rafdulaf** [comment]
et aussi pour ceux utilisant un téléphone

**Comment by rafdulaf** [comment]
Je pense principalement au zoom sur la carte dynamique. Est-ce bien ça ?

**Comment by madcollectordev** [comment]
Je pensais surtout aux règles, et aux aides des cartes

**Comment by rafdulaf** [comment]
oui ok

**Comment by rafdulaf** [comment]
j'ai regardé sur ma tablette, en effet, ça fait petit. 
je vais adapter la police en responsive, mais pas proposer de zoom pour ça.

je suis partisan de limiter le nombre de boutons quitte à brimer certains utilisateurs avancés.
