### ISSUE TITLE
EN : orthographe etc (encore)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#20]
**Ecran "Legend"**

Blue area is the selected area. It has has line of sight to all colored areas.
Yellow areas are below the blue area: Ranged attacks to these areas get an Elevation bonus of 1 yellow die.
Green areas are at the same level as the blue area.
Turquoise areas are above the blue area.
Note: The green circles around the dots show elevation levels.

**Ecran "Boards" (accueil)**

Stygia - Underground
Stygia - Port

**Ecran "Rules"**

Heroes' book
Overlord's book

**Ecran "My expansions"**

Stygia expansion

Campaign book - The Devil in Iron _(préciser le nom du bouquin, il y a déjà plusieurs campagnes fan-made)_
Book of Set

Scenery
-Door pack
-Adventure pack
_(remarque :  est-ce vraiment utile de lister les packs de déco ? zéro impact sur le gameplay)_

**Comment by rafdulaf** [comment]
> Ecran "Legend"
J'ai viré le "s" en trop
> Ecran "Boards" (accueil)
Oui tu me l'avais signalé déjà. C'est corrigé en 0.3 (qui n'est pas encore déployée)
> Ecran "Rules"
Oui tu me l'avais signalé déjà. C'est corrigé en 0.3 (qui n'est pas encore déployée)
> Ecran "My expansions"
Pour la campagne, je précise le nom. Mais cet écran restera dédié que aux extensions officielles, mais pitet que j'en ferai un autre plus tard pour les fanmades. Mais qui c'est, peut-être vont-ils proposer une nouvelle campagne officielle en 2020? :)
