### ISSUE TITLE
Bouton "download cartes statiques"

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#21]
Je trouve que le bouton de "download static lines of sight" n'est pas placé intuitivement. 
Pour moi en toute logique il devrait être sur le même écran que la carte dynamique "lines of sight" (pas sur l'écran "board rules").

**Comment by rafdulaf** [comment]
Je l'ai déplacé au bon endroit. Comme ça fait bcp d'actions, j'ai ouvert un ticket pour regrouper si nécessaire les actions en menu.

Et du coup, vu qu'il y a la place, la rotation de plateau, je la laisse aussi sur les règles.
