### ISSUE TITLE
Creation carte equipement

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#24]
- Pas possible (ou pas trouvé, j'ai cliqué partout) d'ajouter sur la carte les icones CàC, Tir, Défense, Armure, Manip
- Position/Affichage des flèches up-down à recaler.
- Lorsqu'on insère une image, la partie haute du template (avec le nom) est bien au 1er plan, mais pas les bords (c'est un détail mais...).

Sur PC avec Firefox.

Cf screenshot.
![companion web20191005-01](https://user-images.githubusercontent.com/53515040/66253741-fab28b00-e76c-11e9-957f-cba1daaf6255.jpg)

**Comment by rafdulaf** [comment]
pour activer les CàC, Tir et autres, il faut cliquer le point d'interrogation gris, et une liste déroulante des dés apparaît... sur Chrome au moins :) 
je testerai sur firefox rapidement, car j'ai peut être mal fait qqchose.

pour l'image, c'est plus ou moins volontaire qu'elle passe devant le cadre. Les cartes d'équipements fournies avec le jeu le font (j'ai en tête la lance)
pour faire un joli rendu, il vaut mieux utiliser une image sur fond transparent (dans Google images, Outils, Couleur, Transparent)

pour les fléches up/down, en effet ça rend moche sur PC. En fait je teste 90% du temps avec l'émulateur de tablette sur lequel ces flèches n'apparaissent pas.

Merci pour ce retour !

**Comment by RoolzTOL** [comment]
Re-tests studio "carte équipement" sur PC :

- avec Chrome (77), tout marche, et le calage des menus déroulants est un peu mieux que sur FF.
- avec IE (11), message d'erreur "navigateur pas supporté" (je pense que c'est normal / fait exprès :). 
... et...
- avec FF, ça remarche (!?! j'ai touché à rien depuis). Le calage des menus déroulants est toujours bof.

**Comment by rafdulaf** [comment]
Pas de pb non plus avec mon FF.

Je vais juste ajuster les flèches up/down donc.

(IE11 n'est pas supporté en effet, car j'utilise du javascript/html/css moderne - et ma cible est clairement les tablettes - accessoirement les téléphones et les PC portables)
