### ISSUE TITLE
Studio Carte Sort - Vocabulaire (FR)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#38]
Incohérences entre livrets de règles et interface création carte sort:
Coût -> Coût en énergie
Saturation -> Indice de saturation
Texte -> Effet

**Comment by rafdulaf** [comment]
Pris en compte, sauf pour "Saturation" où sur un téléphone en mode portrait, ça ne rentrerait pas d'écrire "Indice de saturation"

**Comment by rafdulaf** [comment]
bon finalement, il y a des tas d'autres choses qui sur un petit écran se mettent sur plusieurs lignes.
donc finalement je garde ta suggestion et sur téléphone l'affichage est un peu déformé mais lisible
