### ISSUE TITLE
Affichage Livre de règles Héros

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#39]
Lorsque j'accède aux vignettes du livre de règle des héros, je clique sur la couverture
Ca m'affiche la couverture à droite.
Je clique sur cette couverture, elle bascule à gauche.
Cela me donne l'impression que la page 1 devrait s'afficher à sa suite à droite. Mais la partie droite reste vide
Voir PJ

Testé sur PC Firefox 71.0
![image](https://user-images.githubusercontent.com/34870193/70731152-85cc7600-1d06-11ea-9b88-b4c37caff222.png)

**Comment by madcollectordev** [comment]
Et quand je clique sur la dernière vignette, affichage de 4 frames mais l'image n'est pas consultable en entier dans la dernière frame
![image](https://user-images.githubusercontent.com/34870193/70731324-cdeb9880-1d06-11ea-8220-0bfbe6a3ad5c.png)

**Comment by rafdulaf** [comment]
sur ta 1ere capture, il y a clairement un bug, car tu n'es jamais censé avoir de scroll horizontal...
tu peux bien effacer le cache du navigateur et recommencer stp ?

(mais j'ai testé pour le moment qu'avec Chrome :) vilain moi)

**Comment by madcollectordev** [comment]
Mon cache est toujours inactif (réflexe d'ancien dev web).
Sur Firefox Beta Android : idem
![image](https://user-images.githubusercontent.com/34870193/70743649-7e19cb00-1d20-11ea-9eae-52418c099ec1.png)

**Comment by rafdulaf** [comment]
ah alors, en effet, j'utilise la css "zoom" qui n'est pas connue de firefox :( 
https://caniuse.com/#search=zoom

je tenterai le transform:scale() comme préconisé 

merci pour le test !

**Comment by rafdulaf** [comment]
Avec un scale et qqs autres propriétés associées j'ai réussi à m'en sortir.
Il reste cependant un problème sur firefox : quand on clique sur une zone pour zoomer : le zoom doit s'effectuer sur la-dite zone ; et là il se met bien plus haut...
Je continue mes investigations

**Comment by rafdulaf** [comment]
C'est bon. ouf.
Firefox traite le zoom de façon vraiment différente :) mais c'est bon
