### ISSUE TITLE
First startup and preferences

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4conan#4]
For example for language:
By default, a french brower will launch the app in french, and it will be in english otherwise.
At first startup, we should propose the user to choose its language

We should display the user how to set its extensions and any other preferences

**Comment by madcollectordev** [comment]
Sur Samsung Galaxy Tab :
- Français proposé par défaut sur Firefox Beta
- Anglais par défaut sur Chrome

=> langage par défaut à demander lors de la première connexion. Pour les personnes qui refusent les cookies, mettre un langage par defaut sans redemander à chaque connexion

**Comment by rafdulaf** [comment]
Je suis étonné que sur ta tablette selon le navigateur tu l'aies un coup en français, un coup en anglais... sauf si ton chrome  est configuré en anglais ? 
(Chrome > Paramètres > Langues : je prends celle en plus haut normalement) Sauf si tu l'avais déjà lancé une fois, ensuite je stocke le choix. Faut effacer les données du site ou utiliser le mode privé pour revenir comme une premier accès

**Comment by Renand** [comment]
A mon niveau sur MacOS 10.14.6 :
EN par défaut, via Chrome Version 76.0.3809.100
FR par défaut,  via Firefox 68.0.1
EN par défaut,  via Safari 12.1.2

**Comment by rafdulaf** [comment]
Et dans le menu "langue" de chaque navigateur, quelle est la valeur la plus haute ? :)
je mise sur EN, FR et EN dans l'ordre :)

**Comment by Renand** [comment]
Dans chrome je suis en Français

![image](https://user-images.githubusercontent.com/738859/62856582-98ea1d80-bcf5-11e9-88b5-a371d5b35e98.png)

Je n'ai pas cette préférence dans Safari (enfin je ne crois pas) Mon système est en FR.

Français également dans Firefox.

![image](https://user-images.githubusercontent.com/738859/62856653-d51d7e00-bcf5-11e9-86a5-1860e6ad81f4.png)

**Comment by rafdulaf** [comment]
ah ok. bien vu. c'est le "français france" (fr_FR) que j'ai pas géré :( 
vilain moi vilain moi vilain moi !

mon test doit s'arrête au code de la langue et ne pas tenir compte du code du pays!
merci
