### ISSUE TITLE
Ergonomie extensions

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#40]
Sous Firefox Beta sur Android, on me propose de sélectionner mes extensions
Les checkbox sont toutes petites et très difficiles à sélectionner
![image](https://user-images.githubusercontent.com/34870193/70743588-5aef1b80-1d20-11ea-8dca-228e45e997a5.png)

**Comment by rafdulaf** [comment]
En effet, on est limite. j'ai vais grossir un peu les choses.
(pour info, le texte est cliquable aussi - pour cocher plus facilement)
