### ISSUE TITLE
Maps statiques à mettre à jour

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#41]
Relance-moi qq jours avant d'ouvrir l'accès, histoire que je me bouge le cul pour mettre à jour les maps "statiques" sur lesquelles on avait vu des erreurs/oublis. 
Comme ça tout sera bien "aligné" entre maps statiques et dynamiques.

**Comment by rafdulaf** [comment]
:) ah ben là je suis chaud patate :)
j'ai corrigé les qqs bugs remontés par @madcollectordev et toi

il y a un dernier truc qui me chiffonne mais je pense d'ici vendredi prochain par exemple

**Comment by rafdulaf** [comment]
Mis à jour dans la prochaine version
