### ISSUE TITLE
Fiche Héros

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#55]
Firefox 75.0 (64 bits)
Cache rechargé

- Image transparente non incluse
- Le clic sur la disquette ne sauvegarde pas. Le bouton retour affiche "vous n'avez aucune fiche"
- Pb d'alignement (voir ronds rouges en PJ)
![image](https://user-images.githubusercontent.com/34870193/81443201-48fd9180-9175-11ea-9205-7f72e3f4e75d.png)

**Comment by rafdulaf** [comment]
Merci et bien vu :)

Mode honte = true ; pour Enregistré et Supprimé ; j'avais juste oublié de les coder, car je visualisais des fiches exportées depuis l'encyclopédie à chaque fois

Pour les flèches qui gène sur PC, j'ai trouvé un moyen pour les virer tout le temps. ça va simplifier le développement PC/Tablette.

Merci. Ca sera corrigé dans la 0.8

**Comment by rafdulaf** [comment]
Et je reproduis bien un problème avec les images sous Firefox

**Comment by rafdulaf** [comment]
Pour info le problème d'image sous Firefox est dû à l'attribut loading="lazy" qui permet de ne pas afficher une image tant qu'elle n'est pas dans le viewport pour charger plus vite... ben là manifestement il y a un bug chez Firefox ;)

**Comment by rafdulaf** [comment]
Bon le lazy loading des images vient à peine d'arriver sur Firefox (c'est depuis la 75) ; et ça n'a pas l'air de marcher correctement du coup.
Dans l'encyclopédie, si je vais voir les héros, seulement certaines images s'affichent... 1 sur 2 en moyenne :( sic

Je vais le désactiver sur Firefox jusqu'à ce qu'il soit mieux supporter

**Comment by madcollectordev** [comment]
Question bête : tu peux pas forcer avec un bouton de formulaire ?
C'est moins joli, mais les gens ont l'habitude de poster leurs images

**Comment by madcollectordev** [comment]
Pour la blague : le rendu sous Epiphany, le navigateur par défaut de Debian
![VirtualBox_Djainette_09_05_2020_19_46_21](https://user-images.githubusercontent.com/34870193/81481098-e0262000-922d-11ea-96aa-8f62ef75ff47.png)

**Comment by rafdulaf** [comment]
Pour l'instant pour les images, je n'ai mis que l'url, mais à terme je supporterai le post de fichiers oui. Je vais ouvrir le ticket d'ailleurs.

Pour le lazy loading, ce n'est aléatoire que sur les fiches de héros. Donc je le désactive seulement là.
