### ISSUE TITLE
EN - Orthographe + Cohérence de vocabulaire entre livrets et appli

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#6]
Ecran "Accueil":
Maps -> Game boards (ou Boards)
Rules :  envoie vers Skills. Normal ?

Ecrans "Maps" (pict village etc):
Line of sight -> Lines of sight
Game help -> Game board rules (ou Board rules)

Ecrans "Game help":
Manque majuscules au début de la plupart des paragraphes.

**Comment by rafdulaf** [comment]
En anglais, tu proposes "Boards". Pq pas. Mais en français j'ai écrit "Cartes"... qu'il faudrait remplacer par "Plateau" ? non ?

**Comment by rafdulaf** [comment]
Ecran d'accueil: Rules renvoie bien vers Rules, qui ne contient qu'un onglet "Skills" pour le moment mais d'autres suivront. Je vais mettre les onglets "en construction" pour ne pas perdre les gens

**Comment by rafdulaf** [comment]
> En anglais, tu proposes "Boards". Pq pas. Mais en français j'ai écrit "Cartes"... qu'il faudrait remplacer par "Plateau" ? non ?

En fait, le mot "Cartes" à l'air plus répandu que "Plateau" en français (en tout cas sur the-overlord :) )

**Comment by rafdulaf** [comment]
> Manque majuscules au début de la plupart des paragraphes.

En fait, en français, je les ai toutes enlevées exprès. Et en anglais j'en avais effectivement oublié...
mais à la reflexion, je vais remettre des majuscules partout :D

**Comment by RoolzTOL** [comment]
_En anglais, tu proposes "Boards". Pq pas. Mais en français j'ai écrit "Cartes"... qu'il faudrait remplacer par "Plateau" ? non ?_
**Oui**
_En fait, le mot "Cartes" à l'air plus répandu que "Plateau" en français (en tout cas sur the-overlord :) )_
**Probablement. Mais je regarde la cohérence par rapport aux livrets de règles (qui sont pour moi la référence). Après tu fais comme tu veux, y'a pas mort d'homme :).**
