### ISSUE TITLE
Coquilles / Précisions (version EN)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#63]
Studio:
Ecran "Print":
A hero sheet is 21cm **(8.3")** wide. If you wan**t** to print with cut margins, you have to print in landscape mode and only 1 sheet at a time. 

(ajouter conversion en pouces + manque un T à want)

My expansions :
Decorations -> **Scenery**

My settings:
Generality -> **General**
Langue de l'interface -> **Language**

My expansions -> Eventuellement changer en "**My game and expansions**" vu que ça permet aussi de sélectionner Core/Retail, Barbarian, ou King. Pareil en français.

Encylopedia :  

Miniatures:
Beêlit -> **Bêlit**

Spells:

Dagon's Attack
Choose a Tentacle in your line of sight. Move that Tentacle **up to** 3 areas, then the Tentacle may perform a Melee Attack.

Eel Skin
Choose a character in your **line** of sight. That character gains Evasive until the end of your next turn.

Push Back
Choose an enemy in your area. Move that enemy **one area**, in a way that would not cause it to suffer damage. This movement is not affected by hindering.
(Texte exact de la carte à revérifier, mais la distance d'1 zone est spécifiée).

**Comment by rafdulaf** [comment]
C'est fait. ça sera pris en compte pour la prochaine version (0.10)
