### ISSUE TITLE
EN+FR - Skills

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#7]
Suggestion : Après le texte de la compétence (idem aides de jeu), ajouter la clarification de cette compétence (idem fin des livrets V2).

**Comment by madcollectordev** [comment]
Est-ce qu'il faut conserver toutes les compétences sur la même page ? Ou utiliser les onglets ? (actuellement un seul onglet)
![image](https://user-images.githubusercontent.com/34870193/62231953-58210900-b3c5-11e9-828c-53d4993d7b44.png)

**Comment by rafdulaf** [comment]
pour les onglets, c'est pq j'envisage de mettre ensuite un résumé des règles pour retrouver rapidement un point précis par exemple.
mais dans une première version, j'avais fait un onglet par type de compétence.

**Comment by rafdulaf** [comment]
pour revenir à la suggestion de départ, normalement le texte des compétences correspond à un mélange du texte des cartes + des clarification du livret v2 (quand il apporte qqchose) + de la traduction de l'autre langue quand celle-ci est plus précise (sur Sacrifice notamment)

Tu as un exemple précis en tête @RoolzTOL ?

**Comment by RoolzTOL** [comment]
OK je viens de relire tous les skills en détail, ça ne n'avait pas sauté aux yeux que tu avais intégré les clarifications. Donc oublie :).
Mais mais mais... je vois des fautes d'anglais ici et là... Je te fais un retour dessus dès que possible (dans ce ticket).

**Comment by rafdulaf** [comment]
quoi ? mon anglais n'est pas irréprochable ? .... les bras m'en tombent ;)

**Comment by RoolzTOL** [comment]
Déjà pour les compétences d'attaque:

Ambidextrous : When this character performs a Melee Attack, the character can choose 2 of their 1-handed weapon cards to attack with. **Cannot be used to perform a Guard action.**

_Si tu écris "do not work for defense" déjà y a une faute :), et en plus c'est ambigu (sachant que la défense dépend de la défense passive "Armor" et active "Guard")._ 

Constriction : [...] move the attacker's **and defender's models together** so their bases touch.[...]

_Pas de faute, mais en reprenant exactement le texte de l'aide de jeu EN tu gagnes des mots/concision/place-écran/lisibilité :)._

Counterattack : [...] this character (if **they're still** alive) may **immediately** counterattack that character [...]

_they est le neutre anglais utilisé dans les livrets. Still donne de la précision. Manque un e à immediately._

Elite shooter :  [...] are not **affected** by hindering [...]

**Comment by rafdulaf** [comment]
> Si tu écris "do not work for defense" déjà y a une faute :), et en plus c'est ambigu (sachant que la défense dépend de la défense passive "Armor" et active "Guard").

Je trouvais ça plus concis. Et puis il y a pas de défense passive avec des armes. Mais ok, je te suis.

> Constriction : [...] move the attacker's **and defender's models together** so their bases touch.[...]

avec cette formulation là, on ne sait pas lequel on doit approcher de l'autre. c'est pour ça que j'avais modifié. cette précision te parait inutile? (ps: j'ai inversé attacker et defender)

> Counterattack : [...] this character (if **they're still** alive) may **immediately** counterattack that character [...]

Je voulais dire: **if still alive** en fait :) mais they c'est le neutre au pluriel si je ne m'abuse ?

**Comment by RoolzTOL** [comment]
> Constriction : [...] move the attacker's and defender's models together so their bases touch.[...]
> 
> avec cette formulation là, on ne sait pas lequel on doit approcher de l'autre. c'est pour ça que j'avais modifié. cette précision te parait inutile? (ps: j'ai inversé attacker et defender)

OK compris. Tu as raison, c'est plus précis (même si plus long). Garde comme ça (modulo l'inversion attaquant/défenseur).

> Counterattack : [...] this character (if they're still alive) may immediately counterattack that character [...]
> 
> Je voulais dire: if still alive en fait :) mais they c'est le neutre au pluriel si je ne m'abuse ?

They c'est le neutre même au singulier aussi (c'est une convention EN récente et assez merdique à mon avis, bref c'est comme ça...). 
Mais "if still alive", c'est effectivement mieux, tu t'affranchis des pbs de genre.

**Comment by rafdulaf** [comment]
Ok.
Du coup, je laisse ce ticket ouvert pour voir si tu as d'autres remarques sur les autres types de compétences.

**Comment by RoolzTOL** [comment]
Compétences de mouvement:

Flying: This character can fly over the elements of the scenery. Flight ignores the movement contraints and penalties of the terrain, and is not affected by hindering.

Climb: This character can move across borders of areas that require this skill, paying the extra movement cost defined by the scenario.

Leap: This character can leap over areas defined by the scenario. The character rolls "1DR", the leap is successful if the die shows symbols equal to or higher than the leap area's difficulty. Leaping costs 1 movement point per crossed area border. For example, when leaping from one ship to another, a character must spend 2 movement points to leap. Leaping is not affected by hindering.

Wall wrecker: This character can spend 2 movement points to move across a wooden wall or door from one area to an adjacent area, and place a "Wall Wrecker" **token** on that obstacle. Then they **immediately** move to the other side of the wall they just wrecked. From now on, the two areas are adjacent, there is no penalty for moving from one to the other, and they have line of sight on each other.

**Comment by RoolzTOL** [comment]
Compétences diverses:

Support: This skill allows friendly characters in the same zone as this character to reroll a single
die for free, each time they **perform** an action,  even if that die has already **been** rerolled (exception to the rule on page 22).

Horror: [...] and Manipulation **actions** of enemy **characters** in this character's area [...]

Concentration:  This character's die **rolls** are not affected[...]

**Comment by RoolzTOL** [comment]
Compétences de défense:

Sacrifice: When a friendly character in this **character's** area is attacked, before **dice** are rolled [...]

Protected: [...] Two or more characters with this skill cannt protect each other.

Bodyguard: [...] The attacked character cannot perform a Guard action, but they can still use thier armor in addition to their bodyguard's defense power.

**Comment by RoolzTOL** [comment]
Compétences de magie:

Spellcaster: [...] Whenever a character **loses** the skill [...]

Teleportation: 
Ce n'est pas une compétence mais un sort, la description du sort est sur la carte, la clarification est en fin de livret V2. Je suggère d'ajouter "Clarification" dans le texte. 
Par exemple "Teleportation: (Clarification) A character who casts this spell [...]"

**Comment by rafdulaf** [comment]
> Sacrifice: When a friendly character in this **character's** area is attacked, before **dice** are rolled [...]

Pour le *die* ou *dice*. Partout dans tous les textes ils utilisent *die* me semble-t-il et d'ailleurs tu n'en a corrigé aucun sauf celui là.... :) pq ?

**Comment by rafdulaf** [comment]
> Protected: [...] Two or more characters with this skill cannot protect each other.

Je l'ajoute. Mais ça me paraissait déjà clair puisqu'on dit : si il n'y a pas d'ami avec Protected.

**Comment by rafdulaf** [comment]
> Bodyguard: [...] The attacked character cannot perform a Guard action, but they can still use their armor in addition to their bodyguard's defense power.

C'est du texte que tu proposes d'ajouter à l'actuel, sans rien retirer ? c'est ça ?

**Comment by RoolzTOL** [comment]
> > Sacrifice: When a friendly character in this **character's** area is attacked, before **dice** are rolled [...]
> 
> Pour le _die_ ou _dice_. Partout dans tous les textes ils utilisent _die_ me semble-t-il et d'ailleurs tu n'en a corrigé aucun sauf celui là.... :) pq ?

Typiquement c'est dice (le pluriel de die) qui est utilisé. "roll the dice / lancer les dés". Ici c'est dice. Pour les autres :
- soit je n'ai pas vu - oups (sur Bodyguard "[...] adding the symbol shown on the **dice** [...]")
- soit c'est une situation où on ne lance qu'un seul dé, auquel cas c'est forcément au singulier, donc die
- soit c'est une erreur dans le texte d'origine (sur Concentration "This character's **dice rolls** are not[...]" ), d'ailleurs celle là je l'avais pas vue non plus- oups aussi.


> > Protected: [...] Two or more characters with this skill cannot protect each other.
> 
> Je l'ajoute. Mais ça me paraissait déjà clair puisqu'on dit : si il n'y a pas d'ami avec Protected.

C'est une clarification justifiée par le fait que si tu as uniquement 2 persos avec Protected dans une zone, le skill ne marche pas. Mais si tu as par exemple 2 persos avec Protected + 1 perso sans Protected dans une zone, là le skill marche (donc il est possible d'avoir un ami avec Protected et que le skill marche qd même :)).

> > Bodyguard: [...] The attacked character cannot perform a Guard action, but they can still use their armor in addition to their bodyguard's defense power.
> 
> C'est du texte que tu proposes d'ajouter à l'actuel, sans rien retirer ? c'est ça ?

Oui c'est ça. C'est le reste de la clarification qu'il y a en fin de livret, je pense que c'est utile. Après tu fais comme tu préfères, pas de souci :).

**Comment by rafdulaf** [comment]
Ok pour "dice" vs "die". Je savais pas 👍 

pour les précisions sur les textes, je vais les ajouter. ça me paraissait clair sans, mais je te suis sur ce coup.

Merci pour ce travail de précision en tous cas !!!

**Comment by rafdulaf** [comment]
finalement sur bodyguard, ça casse pas mal la présentation, et c'est assez redondant, donc je suis revenu en arrière.

**Comment by rafdulaf** [comment]
Plutot que "(Clarification)", je propose "(Clarification of the spell)". Tu valides ?

**Comment by RoolzTOL** [comment]
> Plutot que "(Clarification)", je propose "(Clarification of the spell)". Tu valides ?

"(Spell clarification)". C'est plus anglais et tu économises 2 mots / 7 signes.

**Comment by rafdulaf** [comment]
👍
