### ISSUE TITLE
Affichage tokens encyclopédie

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#76]
Erreur  tokens.js:429:8 

Le return "<a href='javascript:void(0)' onclick='EncyclopediaTokens.openToken(\"" + id + "\")'>" + token.name[Language] + "</a>"; 
n'est pas joignable car return s;
juste avant

conséquence : affichadge d'un jeton blanc

**Comment by rafdulaf** [comment]
pas de lien de cause à effet.
Les tokens ne s'affichent pas sous FF pour une raison qui m'échappe.
Ceci dit j'avais aussi un bug d'url sur ces images que je corrige au passage.
