### ISSUE TITLE
Sorts : dernière ligne tronquée

### ISSUE THREAD

**Issue by madcollectordev** [rafdulaf/companion4conan#77]
![image](https://user-images.githubusercontent.com/34870193/100645913-a50c4b00-333d-11eb-8a7b-b5c3e0518838.png)

**Comment by rafdulaf** [comment]
Ouais, ça je le règle sort par sort : j'adapte la taille du texte à la main. je m'occuperai de celui ci.
mais si tu en vois d'autres...

**Comment by madcollectordev** [comment]
chez moi sont tronqués : 
- Assèchement de la terre
- Guérison de Mitra
- Nuage mortel

Le clic sur une carte de sort affiche la carte au même format. 
Peut-être serait-il judicieux de mettre en dessous le texte complet en police plus grosse ? Pour les vieux qu'ont des mauvais yeux ;)

**Comment by rafdulaf** [comment]
(sous chrome tout est déjà ok. je modifie pour que ça passe sous FireFox)
