### ISSUE TITLE
LOS Grotte

### ISSUE THREAD

**Issue by rafdulaf** [rafdulaf/companion4conan#78]
Les lignes ont disparues entre les cases extérieures ?

**Comment by RoolzTOL** [comment]
Erreur sur ma carte statique des LoS. Avec la règle "Obscurité", toutes les LoS de ce plateau sont annulées, y compris les 3 en bas (même si c'est moins "roleplay").
Je vais mettre à jour la carte statique.

**Comment by rafdulaf** [comment]
ah donc, si c'est y compris les 3 en bas, j'ai rien à faire.
parfait 👍
