### ISSUE TITLE
EN+FR - Menu "My Preferences" [Fixed in 0.2]

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#8]
- Quand on clique sur "My Preferences", "My Expansions" s'affiche en haut.
- Si ce menu est destiné juste à changer la langue, ce serait plus explicite de mettre "Language"à la place. Sinon, "Settings" est plus usité que "Preferences" en anglais.

**Comment by madcollectordev** [comment]
Comme échangé par MP avec @rafdulaf  il devrait y avoir d'autres préférences plus tard
