### ISSUE TITLE
Coquilles VF

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#83]
Encyclo - Autres:

"Pion puit" -> "Pion puits"
"Puit" -> "Puits"

Encyclo - Figurines:
"Animal skin" -> "Peau de bête"
"Bones" -> "Pile de crânes"
"Bookcase" -> "Bibliothèque"
"Sarcophagus" -> "Sarcophage"
"Conan le vagabon" -> "Conan le vagabond" 
"Les Dragons Noirs" -> "Dragons Noirs" (Si possible suivant le code. Et changer aussi l'emplacement de la tuile dans la section Tuiles. La tuile est marquée "Les Dragons Noirs" mais d'un pt de vue lisibilité et recherche dans l'encyclo c'est très bof).
"Les Hommes Noirs" -> "Hommes Noirs" (Idem ci-dessus)
"Spartan" -> Spartiate / Othriades" (Eventuellement mettre la fiche de Héros Othriades dans la section ad'hoc. Fichier pdf dispo sur TOL)

**Comment by rafdulaf** [comment]
pour toutes les miniatures qui sont du décors pur (= ne correspondent à aucun token/tuile/héros) j'ai pas de joli label. j'affiche juste un identifiant (le spartiate en fait partie par ex.)

je vais gérer des libellés pour eux aussi du coup

pour la fiche de héros du spariate justement ; j'ai prévu de faire un tour et d'ajouter aussi celles des chasseurs kushite et d'octavia. later :) 

pour les hommes noirs et les dragons noirs, en effet, on veut pas trier avec le "les" qui est sur les tuiles FR... je vais ajouter ça.

pour le S à puits ; j'avais un tel doute que j'avais MAL cherché ... je sais même pas chercher sur internet :D

**Comment by rafdulaf** [comment]
voilà "Les dragons noirs" ont conservé leur nom de tuile, mais sont triés à côté du "Dragon".

Tous le reste est bon aussi.

Pour le spariate, en fr, j'ai juste mis "Spartiate" mais quand la fiche existera il prendra le double nom

**Comment by RoolzTOL** [comment]
OK vu !
C'est possible de (re) trier aussi dans la section Figurines les dragons noirs (à côté du dragon) et les hommes noirs (à côté de l'homme singe) ?

**Comment by rafdulaf** [comment]
Ouais c'est clair.
Question subsidiaire, dans les sorts en FR, pour Nordheim, ces *@! là ont mis "Le poids des âges"... je vais faire pareil
