### ISSUE TITLE
EN+FR - Menus "Game help" (boards Core box+SG)

### ISSUE THREAD

**Issue by RoolzTOL** [rafdulaf/companion4conan#9]
Dans certain menus "Game help" ("Game board rules"), l'image avec les numéros ne correspond pas à celle du livret V2, il manque des numéros, et/ou les numéros sont mal placés.
Concernés : Pict Village, Inn.
OK : Ships, Abandoned Fort, Citadel, Swamp

Pas vérifié :  Extensions

**Comment by rafdulaf** [comment]
Alors, pour l'auberge, ce sont les tabourets et tables.
Elles ne sont pas représentées sur le fond de carte, donc je n'avais rien de visuel où mettre les points.
Vu que c'est facultatif selon le scénario, on peut se dire que c'est pas grave.
Sinon, il faudra que j'ajoute les tabourets et les tables sur le fond de carte.
Des avis ?

Pour le village picte, par contre c'est clairement un oubli. Vilain rafdulaf.

**Comment by rafdulaf** [comment]
Du coup, j'ai bien vu les numéros manquants. Mais tu parles aussi de "mal placés". Un exemple ?

**Comment by RoolzTOL** [comment]
Sur la map de l'aubverge un n°5 est à côté de l'escalier qu'il est censé indiquer, et certains n°3 sont un peu à côté des murs.

**Comment by rafdulaf** [comment]
oui ok.
Merci. Je corrige
